export { default as Home } from './Home'
export { default as User } from './User'
export { default as Stock} from './Stock'
export { default as Article} from './Article'
export { default as Todos} from './Todos'